---
- name: Setup Minecraft
  ansible.builtin.include_tasks: setup.yml
  tags: setup

- name: Configure backup
  ansible.builtin.include_tasks: backup.yml
  tags: backups

- name: Setup auto-stop
  ansible.builtin.include_tasks: auto-stop.yml